
name: Publish

on:
  # Triggers the workflow on push or pull request events
  # TODO: figure out github token permissions to publish with maven-site plugin
  push:
    branches: [ "none" ]
  pull_request:
    branches: [ "none" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
